spring:
  application:
    name: springboot
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/gsadmin
    username: postgres
    password: 1234
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liwzLxCF1uF0IPKt
            client-secret: 118eb22bcba331b1eef933d8ed8a63e1b671d028
            scope: user:email,read:user
springdoc:
  api-docs:
    path:
      api-docs
logging:
  level:
    root: INFO
    com.back.app: INFO