spring:
  application:
    name: springboot
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres?user=postgres.yukpteahhnmzzspunpoy&password=hjLifDNfcUC0jrwP
    username: postgres
    password: hjLifDNfcUC0jrwP
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23li5fU5lNUFD9mXhP
            client-secret:   5ba2b954f21c8635da9eddf31cb92568f1bdb252
            scope: user:email,read:user
          #google:
            #client-id: GOOGLE_CLIENT_ID
            #client-secret: GOOGLE_CLIENT_SECRET
server:
  forward-headers-strategy: native

logging:
  level:
    root: INFO
    com.back.app: INFO


#ne diraj    
    #hikari:
      #connection-timeout: 30000
      #initialization-fail-timeout: 0
      #maximum-pool-size: 2
  #jpa:
    #hibernate:
      #ddl-auto: none
    #properties:
      #hibernate:
        #dialect: org.hibernate.dialect.PostgreSQLDialect
        #boot:
          #allow_jdbc_metadata_access: false  
    #show-sql: false
  #sql:
    #init:
      #mode: never
#ne diraj    
