spring:
  application:
    name: springboot
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/gsadmin
    username: postgres
    password: 1234


#ne diraj    
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 0
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        boot:
          allow_jdbc_metadata_access: false  
    show-sql: false
  sql:
    init:
      mode: never
#ne diraj    